name: build
on: push
jobs:
  build-native:
    name: Build native libs
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [x86_64]
        include:
          - os: windows-latest
            shell: msys2 {0}
          - os: macos-latest
            shell: bash
          - os: ubuntu-latest
            shell: bash
    env:
      OS_ARCH: ${{ matrix.os }}-${{ matrix.arch }}
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
      OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-latest'
        with:
          install: base-devel gcc
          path-type: inherit
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build native binaries
        if: steps.cache.outputs.cache-hit != 'true' && matrix.os != 'ubuntu-latest'
        run: bash build.sh
      - name: Build native binaries in centos container
        if: steps.cache.outputs.cache-hit != 'true' && matrix.os == 'ubuntu-latest'
        uses: docker://ghcr.io/gliwka/centos6-devtoolset7:main
        with:
          args: build.sh